[tool.poetry]
name = "gdutils"
version = "0.2.0"
description = "A collection of useful utility functions"
authors = ["Greg Detre <greg@gregdetre.co.uk>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.5"
pandas = "^1.3.5"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
