[tool.poetry]
name = "gdutils"
version = "0.4.1"
description = "A collection of useful utility functions (strings, dates, data science, types, etc)"
authors = [
    "Greg Detre <greg@gregdetre.co.uk>"
]
homepage = "https://github.com/gregdetre/gdutils"
repository = "https://github.com/gregdetre/gdutils"
license = "MIT"
readme = "README.md"
keywords = ["utilities", "strings", "dates", "data science"]
classifiers = [
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.5"
pandas = "^1.3.5"
pendulum = "^2.1.2"
ipdb = "^0.13.9"
openai = "^0.11.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
